services:
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - inventory-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://inventory_user:inventory_pass@db:5432/inventory_db?sslmode=disable
      JWT_SECRET: your_super_secure_jwt_secret_key_change_in_production
      PORT: 8080
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - inventory-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - inventory-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  inventory-network:
    driver: bridge
